ALTER TABLE organizations
ADD COLUMN IF NOT EXISTS page_about TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS page_terms TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS page_contacts TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS whatsapp_phone TEXT DEFAULT '';
